/**
 * Loot tables for crates & NPCs — full item lists with drop chance and amount.
 * Sourced from the official Facepunch wiki loot tables.
 */

import { iconUrlFromName } from './items';

export interface LootEntry {
  item: string;
  chance: string;
  amount?: string;
}

export interface LootTable {
  id: string;
  name: string;
  note?: string;
  entries: LootEntry[];
}

export const LOOT_TABLES: Record<string, LootTable> = {
  // ── Military Crate (crate_normal) — 108 items ──
  military: {
    id: 'military',
    name: 'Military Crate',
    note: 'Tier 2-3 monuments. 6 slots. Always drops Scrap.',
    entries: [
      { item: 'Scrap', chance: '100%', amount: 'x8' },
      { item: 'High Quality Metal', chance: '16.7%', amount: 'x15-25' },
      { item: 'Metal Pipe', chance: '16.7%', amount: 'x5-6' },
      { item: 'Rifle Body', chance: '16.7%', amount: 'x1' },
      { item: 'SMG Body', chance: '16.7%', amount: 'x1' },
      { item: 'Tech Trash', chance: '16.7%', amount: 'x2-4' },
      { item: 'Basic Blueprint Fragment', chance: '10.0%', amount: 'x1' },
      { item: 'Targeting Computer', chance: '8.7%', amount: 'x1' },
      { item: 'CCTV Camera', chance: '7.1%', amount: 'x1' },
      { item: 'Large Backpack', chance: '5.0%', amount: 'x1' },
      { item: 'Metal Armor Insert', chance: '5.0%', amount: 'x1' },
      { item: 'Auto Turret', chance: '1.2%', amount: 'x1' },
      { item: 'Supply Signal', chance: '1.0%', amount: 'x1' },
      { item: 'Hazmat Suit', chance: '0.4%', amount: 'x1' },
      { item: 'Heavy Plate Helmet / Jacket / Pants', chance: '0.4% ea', amount: 'x1' },
      { item: 'Thompson / Custom SMG / Pump Shotgun', chance: '0.4% ea', amount: 'x1' },
      { item: 'High Caliber / Python Revolver', chance: '0.4% ea', amount: 'x1' },
      { item: 'Semi-Auto Pistol / Rifle', chance: '0.4% ea', amount: 'x1' },
      { item: 'Rocket Launcher / Homing Missile Launcher', chance: '0.4% ea', amount: 'x1' },
      { item: 'Chainsaw / Flame Thrower / Longsword', chance: '0.4% ea', amount: 'x1' },
      { item: 'F1 Grenade / Flashbang / Molotov / Smoke', chance: '0.4% ea', amount: 'x1' },
      { item: 'Night Vision Goggles', chance: '0.4%', amount: 'x1' },
      { item: 'Garage Door / Ladder Hatch / Armored pieces', chance: '0.4% ea', amount: 'x1' },
      { item: 'Electrical & deployables (turret, batteries, etc.)', chance: '0.4% ea', amount: 'x1' },
      { item: 'Other rare attire / tools / construction', chance: '0.4% ea', amount: 'x1' },
    ],
  },

  // Tier-3 alias still points at the elite-style richer table.
  military_t3: {
    id: 'military_t3',
    name: 'Military Crate (Tier 3)',
    note: 'Uses the same table as the Military Crate, denser at tier-3 monuments.',
    entries: [
      { item: 'Scrap', chance: '100%', amount: 'x8' },
      { item: 'High Quality Metal', chance: '16.7%', amount: 'x15-25' },
      { item: 'Metal Pipe', chance: '16.7%', amount: 'x5-6' },
      { item: 'Rifle Body / SMG Body', chance: '16.7% ea', amount: 'x1' },
      { item: 'Tech Trash', chance: '16.7%', amount: 'x2-4' },
      { item: 'Basic Blueprint Fragment', chance: '10.0%', amount: 'x1' },
      { item: 'Targeting Computer', chance: '8.7%', amount: 'x1' },
      { item: 'CCTV Camera', chance: '7.1%', amount: 'x1' },
      { item: 'Metal Armor Insert / Large Backpack', chance: '5.0% ea', amount: 'x1' },
      { item: 'Auto Turret', chance: '1.2%', amount: 'x1' },
      { item: 'Supply Signal', chance: '1.0%', amount: 'x1' },
      { item: 'Weapons / armor / deployables (each)', chance: '0.4% ea', amount: 'x1' },
    ],
  },

  // ── Elite Crate (crate_elite) — 137 items ──
  elite: {
    id: 'elite',
    name: 'Elite Crate',
    note: 'Tier-3 only (Launch Site, Military Tunnel, Oil Rigs, Missile Silo). 5 slots.',
    entries: [
      { item: 'Scrap', chance: '100%', amount: 'x25' },
      { item: 'High Quality Metal', chance: '27.7%', amount: 'x15-50' },
      { item: 'Metal Pipe', chance: '27.7%', amount: 'x5-12' },
      { item: 'Rifle Body', chance: '27.7%', amount: 'x1-2' },
      { item: 'SMG Body', chance: '27.7%', amount: 'x1-2' },
      { item: 'Tech Trash', chance: '27.7%', amount: 'x2-8' },
      { item: 'MLRS Rocket', chance: '20.0%', amount: 'x1-2' },
      { item: 'Targeting Computer', chance: '15.3%', amount: 'x1-2' },
      { item: 'CCTV Camera', chance: '12.6%', amount: 'x1-2' },
      { item: 'Advanced Blueprint Fragment', chance: '10.0%', amount: 'x1' },
      { item: 'Pistol Bullet', chance: '9.5%', amount: 'x15-48' },
      { item: '12 Gauge Buckshot', chance: '8.3%', amount: 'x5-12' },
      { item: 'F1 Grenade', chance: '7.2%', amount: 'x1-2' },
      { item: 'Flame Thrower', chance: '7.2%', amount: 'x1-2' },
      { item: 'Flashbang', chance: '7.2%', amount: 'x1-2' },
      { item: 'Molotov Cocktail', chance: '7.2%', amount: 'x1-2' },
      { item: 'Semi-Automatic Pistol', chance: '7.2%', amount: 'x1-2' },
      { item: '5.56 Rifle Ammo', chance: '7.0%', amount: 'x8-50' },
      { item: 'Beancan Grenade', chance: '6.5%', amount: 'x1' },
      { item: 'Double Barrel Shotgun', chance: '6.5%', amount: 'x1' },
      { item: 'Low Grade Fuel', chance: '6.5%', amount: 'x35' },
      { item: 'Assault Rifle', chance: '4.4%', amount: 'x1-2' },
      { item: 'Bolt Action Rifle', chance: '4.4%', amount: 'x1-2' },
      { item: 'MP5A4', chance: '4.4%', amount: 'x1-2' },
      { item: 'Supply Signal', chance: '3.7%', amount: 'x1-2' },
      { item: 'Custom SMG', chance: '2.8%', amount: 'x1-2' },
      { item: 'Thompson', chance: '2.8%', amount: 'x1-2' },
      { item: '8x Zoom Scope', chance: '2.4%', amount: 'x1-2' },
      { item: 'Armored Door / Double Door', chance: '2.4% ea', amount: 'x1-2' },
      { item: 'Explosives', chance: '2.4%', amount: 'x1-2' },
      { item: 'HMLMG', chance: '2.4%', amount: 'x1-2' },
      { item: 'Metal Chest Plate / Facemask', chance: '2.4% ea', amount: 'x1-2' },
      { item: 'Military Silencer', chance: '2.4%', amount: 'x1-2' },
      { item: 'SKS', chance: '2.4%', amount: 'x1-2' },
      { item: 'Timed Explosive Charge (C4)', chance: '2.4%', amount: 'x1-2' },
      { item: 'Weapon Lasersight', chance: '2.4%', amount: 'x1-2' },
      { item: 'Auto Turret', chance: '2.2%', amount: 'x1-2' },
      { item: 'M92 Pistol', chance: '2.0%', amount: 'x1' },
      { item: 'Prototype 17', chance: '2.0%', amount: 'x1' },
      { item: '12 Gauge Slug', chance: '1.2%', amount: 'x8-12' },
      { item: 'LR-300 Assault Rifle', chance: '1.2%', amount: 'x1' },
      { item: 'M39 Rifle', chance: '1.2%', amount: 'x1' },
      { item: 'M4 Shotgun', chance: '1.2%', amount: 'x1' },
      { item: 'L96 Rifle', chance: '0.8%', amount: 'x1' },
      { item: 'Spas-12 Shotgun', chance: '0.8%', amount: 'x1' },
      { item: 'Variable Zoom Scope', chance: '0.8%', amount: 'x1' },
      { item: 'Heavy Plate armor / NVG / other rares', chance: '0.8% ea', amount: 'x1-2' },
    ],
  },

  // ── Brown / Normal Crate (crate_normal_2) — 121 items ──
  basic: {
    id: 'basic',
    name: 'Normal / Basic Crate',
    note: 'Tier-1 monuments & roadside. 6 slots. Components, the Electric Fuse & diving gear.',
    entries: [
      { item: 'Scrap', chance: '100%', amount: 'x5' },
      { item: 'Electric Fuse', chance: '14.3%', amount: 'x1' },
      { item: 'Gears', chance: '14.3%', amount: 'x2-3' },
      { item: 'Metal Pipe', chance: '14.3%', amount: 'x1-5' },
      { item: 'Metal Spring', chance: '14.3%', amount: 'x1-2' },
      { item: 'Road Signs', chance: '14.3%', amount: 'x2-4' },
      { item: 'Semi Automatic Body', chance: '14.3%', amount: 'x1' },
      { item: 'Sheet Metal', chance: '14.3%', amount: 'x1-2' },
      { item: 'Diving Mask', chance: '4.2%', amount: 'x1' },
      { item: 'Hazmat Suit', chance: '4.0%', amount: 'x1' },
      { item: 'Diving Tank', chance: '2.5%', amount: 'x1' },
      { item: 'Targeting Computer', chance: '2.1%', amount: 'x1' },
      { item: 'CCTV Camera', chance: '1.7%', amount: 'x1' },
      { item: 'Diving Fins', chance: '1.7%', amount: 'x1' },
      { item: 'Wetsuit', chance: '1.7%', amount: 'x1' },
      { item: 'Large Solar Panel', chance: '1.5%', amount: 'x1' },
      { item: 'Electrical components (switches, batteries, etc.)', chance: '1.3% ea', amount: 'x1' },
      { item: 'Door Controller / Flasher / Siren Light', chance: '0.7% ea', amount: 'x1' },
      { item: 'Weapons (Revolver, Handmade SMG, Compound Bow…)', chance: '0.4% ea', amount: 'x1' },
      { item: 'Satchel Charge / Beancan Grenade', chance: '0.4% ea', amount: 'x1' },
      { item: 'Attire / tools / construction / deployables', chance: '0.4% ea', amount: 'x1' },
      { item: 'RF & advanced electrical (rare)', chance: '0.1-0.3% ea', amount: 'x1' },
    ],
  },

  // ── Locked Crate (codelockedhackablecrate) — 136 items ──
  locked: {
    id: 'locked',
    name: 'Locked Crate (Hackable)',
    note: 'Cargo Ship, Chinook, Oil Rigs. 15-min hack, 19 slots. Best guaranteed loot.',
    entries: [
      { item: 'Advanced Blueprint Fragment', chance: '100%', amount: 'x2' },
      { item: 'Metal Armor Insert', chance: '100%', amount: 'x1' },
      { item: 'Targeting Computer', chance: '55.3%', amount: 'x1' },
      { item: 'Metal Chest Plate', chance: '52.8%', amount: 'x1' },
      { item: 'Metal Facemask', chance: '52.8%', amount: 'x1' },
      { item: 'MLRS Aiming Module', chance: '50.0%', amount: 'x1' },
      { item: 'CCTV Camera', chance: '45.7%', amount: 'x1' },
      { item: 'High Quality Metal', chance: '41.1%', amount: 'x15-40' },
      { item: 'Metal Pipe', chance: '39.3%', amount: 'x5-6' },
      { item: 'Tech Trash', chance: '39.3%', amount: 'x2-5' },
      { item: '5.56 Rifle Ammo', chance: '37.0%', amount: 'x50-120' },
      { item: 'Explosive 5.56 Ammo', chance: '33.9%', amount: 'x1-30' },
      { item: 'HV 5.56 Ammo', chance: '33.9%', amount: 'x1-40' },
      { item: 'Incendiary 5.56 Ammo', chance: '33.9%', amount: 'x1-60' },
      { item: 'Scrap', chance: '33.3%', amount: 'x140-160' },
      { item: 'Assault Rifle', chance: '31.6%', amount: 'x1' },
      { item: 'Gears', chance: '31.2%', amount: 'x5' },
      { item: 'Sheet Metal', chance: '31.2%', amount: 'x5' },
      { item: '8x Zoom Scope', chance: '29.2%', amount: 'x1' },
      { item: 'Weapon Lasersight', chance: '29.2%', amount: 'x1' },
      { item: 'LR-300 Assault Rifle', chance: '27.6%', amount: 'x1' },
      { item: 'Extended Magazine', chance: '26.0%', amount: 'x1' },
      { item: 'Bolt Action Rifle', chance: '25.1%', amount: 'x1' },
      { item: 'Burst Module', chance: '25.0%', amount: 'x1' },
      { item: 'Auto Turret', chance: '15.9%', amount: 'x1' },
      { item: 'Rifle Body / SMG Body', chance: '11.7% ea', amount: 'x1' },
      { item: 'M4 Shotgun', chance: '10.3%', amount: 'x1' },
      { item: 'Minigun', chance: '10.0%', amount: 'x1' },
      { item: 'F1 Grenade', chance: '9.8%', amount: 'x1-4' },
      { item: 'Timed Explosive Charge (C4)', chance: '9.6%', amount: 'x1' },
      { item: 'Satchel Charge', chance: '8.6%', amount: 'x1' },
      { item: 'Rocket Launcher', chance: '8.1%', amount: 'x1' },
      { item: 'L96 Rifle', chance: '6.9%', amount: 'x1' },
      { item: 'Chainsaw', chance: '5.6%', amount: 'x1' },
      { item: 'Armored Door / Double Door', chance: '5.6% ea', amount: 'x1' },
      { item: 'Explosives', chance: '5.6%', amount: 'x1' },
      { item: 'HMLMG / MP5A4 / SKS', chance: '5.6% ea', amount: 'x1' },
      { item: 'Reinforced Glass Window', chance: '5.6%', amount: 'x1' },
      { item: 'Rocket', chance: '5.6%', amount: 'x1' },
      { item: 'Jackhammer', chance: '4.3%', amount: 'x1' },
      { item: 'Supply Signal', chance: '1.4%', amount: 'x1' },
      { item: 'Other rare weapons / armor / deployables', chance: '1.3% ea', amount: 'x1' },
    ],
  },

  // ── Helicopter Crate (heli_crate) — 40 items ──
  heli_crate: {
    id: 'heli_crate',
    name: 'Helicopter Crate',
    note: '4 drop from a downed Patrol Helicopter (burning — wait to loot).',
    entries: [
      { item: '5.56 Rifle Ammo', chance: '27.7%', amount: 'x8-120' },
      { item: 'Timed Explosive Charge (C4)', chance: '25.6%', amount: 'x1-2' },
      { item: 'Rocket', chance: '25.0%', amount: 'x3' },
      { item: 'Explosive 5.56 Ammo', chance: '15.0%', amount: 'x30' },
      { item: 'High Velocity Rocket', chance: '15.0%', amount: 'x3' },
      { item: 'Homing Missile', chance: '15.0%', amount: 'x4' },
      { item: 'HV 5.56 Ammo', chance: '15.0%', amount: 'x40' },
      { item: 'Incendiary 5.56 Ammo', chance: '15.0%', amount: 'x60' },
      { item: 'Incendiary Rocket', chance: '15.0%', amount: 'x5' },
      { item: 'MLRS Rocket', chance: '15.0%', amount: 'x2' },
      { item: 'M249', chance: '10.0%', amount: 'x1' },
      { item: '8x Zoom Scope', chance: '8.3%', amount: 'x1' },
      { item: 'Weapon Lasersight', chance: '8.3%', amount: 'x1' },
      { item: 'Pistol Bullet', chance: '7.6%', amount: 'x15-48' },
      { item: 'Burst Module', chance: '7.5%', amount: 'x1' },
      { item: 'Extended Magazine', chance: '7.5%', amount: 'x1' },
      { item: 'Assault Rifle', chance: '2.4%', amount: 'x1' },
      { item: 'Bolt Action Rifle', chance: '2.4%', amount: 'x1' },
      { item: 'MP5A4', chance: '2.4%', amount: 'x1' },
      { item: 'Custom SMG', chance: '1.6%', amount: 'x1' },
      { item: 'M92 Pistol', chance: '1.6%', amount: 'x1' },
      { item: 'Prototype 17', chance: '1.6%', amount: 'x1' },
      { item: 'Thompson', chance: '1.6%', amount: 'x1' },
      { item: '12 Gauge Buckshot', chance: '1.6%', amount: 'x8-12' },
      { item: '12 Gauge Slug', chance: '0.9%', amount: 'x8-12' },
      { item: 'LR-300 / M39 / M4 Shotgun', chance: '0.9% ea', amount: 'x1' },
      { item: 'Armored Door / Double Door', chance: '0.8% ea', amount: 'x1' },
      { item: 'Explosives / HMLMG', chance: '0.8% ea', amount: 'x1' },
      { item: 'Metal Chest Plate / Facemask', chance: '0.8% ea', amount: 'x1' },
      { item: 'Military Silencer / Reinforced Glass / SKS', chance: '0.8% ea', amount: 'x1' },
      { item: 'L96 Rifle / Spas-12 / Variable Zoom Scope', chance: '0.6% ea', amount: 'x1' },
    ],
  },

  // ── Patrol Heli fuselage gibs (heli_body) — farm the wreck after looting ──
  heli_body: {
    id: 'heli_body',
    name: 'Helicopter Debris',
    note: 'Harvest the burnt-out fuselage with a tool once the fire dies down.',
    entries: [
      { item: 'High Quality Metal', chance: '100%', amount: 'x100-150' },
      { item: 'Metal Fragments', chance: '100%', amount: 'x600-1000' },
      { item: 'Charcoal', chance: '100%', amount: 'x500-1000' },
      { item: 'Scrap', chance: '100%', amount: 'x25-50' },
      { item: 'Crude Oil', chance: '60%', amount: 'x10-30' },
    ],
  },

  apc_crate: {
    id: 'apc_crate',
    name: 'Bradley (APC) Crate',
    note: '3 drop from a destroyed Bradley APC at Launch Site (burning). 7 slots.',
    entries: [
      { item: 'MLRS Rocket', chance: '100%', amount: 'x1-4' },
      { item: 'Targeting Computer', chance: '52.4%', amount: 'x1' },
      { item: '8x Zoom Scope', chance: '50.0%', amount: 'x1' },
      { item: 'Burst Module', chance: '50.0%', amount: 'x1' },
      { item: 'Extended Magazine', chance: '50.0%', amount: 'x1' },
      { item: 'Weapon Lasersight', chance: '50.0%', amount: 'x1' },
      { item: 'CCTV Camera', chance: '42.9%', amount: 'x1' },
      { item: '5.56 Rifle Ammo', chance: '30.0%', amount: 'x8-240' },
      { item: 'Armored Door', chance: '30.0%', amount: 'x1' },
      { item: 'Ladder Hatch', chance: '30.0%', amount: 'x1' },
      { item: 'Timed Explosive Charge (C4)', chance: '27.3%', amount: 'x1-2' },
      { item: 'Tech Trash', chance: '25.0%', amount: 'x10-12' },
      { item: 'Explosive 5.56 Ammo', chance: '17.5%', amount: 'x30-60' },
      { item: 'High Velocity Rocket', chance: '17.5%', amount: 'x3-6' },
      { item: 'Homing Missile', chance: '17.5%', amount: 'x4-8' },
      { item: 'HV 5.56 Ammo', chance: '17.5%', amount: 'x40-80' },
      { item: 'Incendiary 5.56 Ammo', chance: '17.5%', amount: 'x60-120' },
      { item: 'Incendiary Rocket', chance: '17.5%', amount: 'x5-10' },
      { item: 'Armored Double Door', chance: '15.0%', amount: 'x1' },
      { item: 'L96 Rifle', chance: '8.6%', amount: 'x1' },
      { item: 'Variable Zoom Scope', chance: '8.6%', amount: 'x1' },
      { item: 'M249', chance: '8.3%', amount: 'x1' },
      { item: 'Auto Turret', chance: '4.8%', amount: 'x1' },
      { item: 'Pistol Bullet', chance: '4.0%', amount: 'x15-48' },
      { item: 'Assault Rifle / Bolt / MP5 / Thompson', chance: '0.9% ea', amount: 'x1' },
      { item: 'Custom SMG / M92 / Prototype 17', chance: '0.9% ea', amount: 'x1' },
      { item: '12 Gauge Buckshot', chance: '0.9%', amount: 'x8-12' },
      { item: '12 Gauge Slug / LR-300 / M39 / M4 Shotgun', chance: '0.5% ea', amount: 'x1' },
      { item: 'Spas-12 Shotgun', chance: '0.3%', amount: 'x1' },
    ],
  },

  // ── Scientist (scientistnpc_full_any) — 18 items ──
  scientist: {
    id: 'scientist',
    name: 'Scientist (NPC)',
    note: 'Dropped on death. Guards most tier 2-3 monuments. Can drop a Green Keycard.',
    entries: [
      { item: 'Flare', chance: '36.3%', amount: 'x4-12' },
      { item: 'Green Keycard', chance: '36.3%', amount: 'x1-2' },
      { item: 'Medical Syringe', chance: '36.3%', amount: 'x1-2' },
      { item: 'Pickaxe', chance: '36.3%', amount: 'x1-2' },
      { item: 'Scrap', chance: '36.3%', amount: 'x8-24' },
      { item: 'Semi Automatic Body', chance: '36.3%', amount: 'x1-2' },
      { item: 'Rifle Body', chance: '4.1%', amount: 'x1' },
      { item: 'MP5A4', chance: '3.3%', amount: 'x1' },
      { item: 'Pistol Bullet', chance: '3.3%', amount: 'x30' },
      { item: '12 Gauge Incendiary Shell', chance: '2.9%', amount: 'x4-8' },
      { item: 'F1 Grenade', chance: '2.9%', amount: 'x2-4' },
      { item: 'Hazmat Suit', chance: '2.9%', amount: 'x1' },
      { item: 'SMG Body', chance: '2.9%', amount: 'x1' },
      { item: 'Tech Trash', chance: '2.9%', amount: 'x1' },
      { item: 'Weapon Flashlight', chance: '2.9%', amount: 'x1' },
      { item: 'Asbestos Armor Insert', chance: '1.4%', amount: 'x1' },
      { item: 'Lead Armor Insert', chance: '1.0%', amount: 'x1' },
      { item: 'Metal Armor Insert', chance: '0.4%', amount: 'x1' },
    ],
  },

  // ── Heavy Scientist (scientistnpc_heavy) — 147 items ──
  heavy_scientist: {
    id: 'heavy_scientist',
    name: 'Heavy Scientist (NPC)',
    note: 'Tanky armored guards (Launch Site, Oil Rigs, Military Tunnel, Excavator).',
    entries: [
      { item: 'Medical Syringe', chance: '88.9%', amount: 'x1-4' },
      { item: 'Pistol Bullet', chance: '60.9%', amount: 'x15-48' },
      { item: 'Bandage', chance: '55.6%', amount: 'x1-2' },
      { item: '12 Gauge Buckshot', chance: '48.7%', amount: 'x5-18' },
      { item: '5.56 Rifle Ammo', chance: '46.8%', amount: 'x8-50' },
      { item: '12 Gauge Slug', chance: '29.9%', amount: 'x4-12' },
      { item: '12 Gauge Incendiary Shell', chance: '29.3%', amount: 'x4-24' },
      { item: 'Incendiary Pistol Bullet', chance: '27.1%', amount: 'x10-30' },
      { item: 'Low Grade Fuel', chance: '24.0%', amount: 'x35-100' },
      { item: 'Military Flame Thrower', chance: '20.0%', amount: 'x1' },
      { item: 'Minigun', chance: '20.0%', amount: 'x1' },
      { item: '40mm Shotgun Round', chance: '15.1%', amount: 'x4-24' },
      { item: '40mm Smoke Grenade', chance: '15.1%', amount: 'x2-12' },
      { item: 'HV Pistol Ammo', chance: '14.3%', amount: 'x10-30' },
      { item: 'Incendiary 5.56 Ammo', chance: '12.7%', amount: 'x8-24' },
      { item: '40mm HE Grenade', chance: '11.6%', amount: 'x2-12' },
      { item: 'Explosive 5.56 Ammo', chance: '6.5%', amount: 'x8-24' },
      { item: 'HV 5.56 Ammo', chance: '6.5%', amount: 'x10-30' },
      { item: 'F1 Grenade / Flashbang / Molotov', chance: '5.1% ea', amount: 'x1' },
      { item: 'Flame Thrower', chance: '5.1%', amount: 'x1' },
      { item: 'Semi-Automatic Pistol', chance: '5.1%', amount: 'x1' },
      { item: 'Beancan Grenade', chance: '5.0%', amount: 'x1' },
      { item: 'Double Barrel Shotgun', chance: '5.0%', amount: 'x1' },
      { item: 'Multiple Grenade Launcher', chance: '5.0%', amount: 'x1' },
      { item: 'High Quality Metal', chance: '2.4%', amount: 'x15-25' },
      { item: 'Metal Pipe', chance: '2.4%', amount: 'x5-6' },
      { item: 'Rifle Body / SMG Body', chance: '2.4% ea', amount: 'x1' },
      { item: 'Tech Trash', chance: '2.4%', amount: 'x2-4' },
      { item: 'Assault Rifle / Bolt Action Rifle / MP5A4', chance: '1.9% ea', amount: 'x1' },
      { item: 'Custom SMG / Thompson', chance: '1.6% ea', amount: 'x1' },
      { item: 'M92 Pistol / Prototype 17', chance: '1.6% ea', amount: 'x1' },
      { item: 'Targeting Computer', chance: '1.2%', amount: 'x1' },
      { item: 'CCTV Camera', chance: '1.0%', amount: 'x1' },
      { item: 'LR-300 / M39 / M4 Shotgun', chance: '0.9% ea', amount: 'x1' },
      { item: 'L96 Rifle / Spas-12 / Variable Zoom Scope', chance: '0.6% ea', amount: 'x1' },
      { item: 'Metal Chest Plate / Facemask / Heavy Plate armor', chance: '0.1-0.3% ea', amount: 'x1' },
      { item: 'Explosives / C4 / Rocket Launcher', chance: '0.1-0.3% ea', amount: 'x1' },
      { item: 'Other rare weapons / deployables / electrical', chance: '0.1% ea', amount: 'x1' },
    ],
  },
};

export function getLootTable(id: string): LootTable | null {
  return LOOT_TABLES[id] || null;
}

/**
 * Maps a loot-entry display name to its rusthelp CDN icon slug. Returns null
 * for grouped/multi-item rows (e.g. "Rifle Body / SMG Body") so they render
 * without an icon. Icons are served from cdn.rusthelp.com/images/128/<slug>.webp
 */
const LOOT_ICON_SLUGS: Record<string, string> = {
  'scrap': 'scrap',
  'high quality metal': 'metal-refined',
  'metal fragments': 'metal-fragments',
  'charcoal': 'charcoal',
  'crude oil': 'crude-oil',
  'metal pipe': 'metalpipe',
  'metal spring': 'metalspring',
  'rifle body': 'riflebody',
  'smg body': 'smgbody',
  'semi automatic body': 'semibody',
  'tech trash': 'techparts',
  'gears': 'gears',
  'road signs': 'roadsigns',
  'sheet metal': 'sheetmetal',
  'basic blueprint fragment': 'basicblueprintfragment',
  'advanced blueprint fragment': 'advancedblueprintfragment',
  'targeting computer': 'targeting-computer',
  'cctv camera': 'cctv-camera',
  'metal armor insert': 'clothing-mod-armorinsert-metal',
  'large backpack': 'largebackpack',
  'auto turret': 'autoturret',
  'supply signal': 'supply-signal',
  'hazmat suit': 'hazmatsuit',
  'electric fuse': 'fuse',
  'mlrs rocket': 'ammo-rocket-mlrs',
  'mlrs aiming module': 'aiming-module-mlrs',
  'rocket': 'ammo-rocket-basic',
  'high velocity rocket': 'ammo-rocket-hv',
  'incendiary rocket': 'ammo-rocket-fire',
  'homing missile': 'ammo-rocket-seeker',
  '5.56 rifle ammo': 'ammo-rifle',
  'explosive 5.56 ammo': 'ammo-rifle-explosive',
  'hv 5.56 ammo': 'ammo-rifle-hv',
  'incendiary 5.56 ammo': 'ammo-rifle-incendiary',
  'pistol bullet': 'ammo-pistol',
  'hv pistol ammo': 'ammo-pistol-hv',
  'incendiary pistol bullet': 'ammo-pistol-fire',
  '12 gauge buckshot': 'ammo-shotgun',
  '12 gauge slug': 'ammo-shotgun-slug',
  '12 gauge incendiary shell': 'ammo-shotgun-fire',
  '40mm shotgun round': 'ammo-grenadelauncher-buckshot',
  '40mm he grenade': 'ammo-grenadelauncher-he',
  '40mm smoke grenade': 'ammo-grenadelauncher-smoke',
  'low grade fuel': 'lowgradefuel',
  'timed explosive charge (c4)': 'explosive-timed',
  'satchel charge': 'explosive-satchel',
  'explosives': 'explosives',
  'f1 grenade': 'grenade-f1',
  'beancan grenade': 'grenade-beancan',
  'molotov cocktail': 'molotov',
  'flashbang': 'grenade-flashbang',
  'smoke grenade': 'grenade-smoke',
  'assault rifle': 'rifle-ak',
  'lr-300 assault rifle': 'rifle-lr300',
  'bolt action rifle': 'rifle-bolt',
  'l96 rifle': 'rifle-l96',
  'm39 rifle': 'rifle-m39',
  'sks': 'rifle-semiauto',
  'semi-automatic rifle': 'rifle-semiauto',
  'mp5a4': 'smg-mp5',
  'custom smg': 'smg-2',
  'thompson': 'smg-thompson',
  'm249': 'lmg-m249',
  'hmlmg': 'hmlmg',
  'minigun': 'minigun',
  'm4 shotgun': 'shotgun-m4',
  'spas-12 shotgun': 'shotgun-spas12',
  'double barrel shotgun': 'shotgun-double',
  'pump shotgun': 'shotgun-pump',
  'semi-automatic pistol': 'pistol-semiauto',
  'm92 pistol': 'pistol-m92',
  'python revolver': 'pistol-python',
  'high caliber revolver': 'pistol-revolver',
  'prototype 17': 'pistol-prototype17',
  'flame thrower': 'flamethrower',
  'military flame thrower': 'flamethrower',
  'multiple grenade launcher': 'multiplegrenadelauncher',
  'rocket launcher': 'rocket-launcher',
  'chainsaw': 'chainsaw',
  'jackhammer': 'jackhammer',
  'metal chest plate': 'metal-plate-torso',
  'metal facemask': 'metal-facemask',
  '8x zoom scope': 'weapon-mod-8x-scope',
  'variable zoom scope': 'weapon-mod-small-scope',
  'weapon lasersight': 'weapon-mod-lasersight',
  'military silencer': 'weapon-mod-silencer',
  'extended magazine': 'weapon-mod-extendedmags',
  'burst module': 'weapon-mod-burstmodule',
  'medical syringe': 'syringe-medical',
  'bandage': 'bandage',
  'large medkit': 'largemedkit',
  'green keycard': 'keycard-green',
  'pickaxe': 'pickaxe',
  'flare': 'flare',
  'armored door': 'door-hinged-toptier',
  'ladder hatch': 'floor-ladder-hatch',
  'reinforced glass window': 'wall-window-glass-reinforced',
};

export function lootIconUrl(name: string): string | null {
  const slug = LOOT_ICON_SLUGS[name.trim().toLowerCase()];
  if (slug) return `https://cdn.rusthelp.com/images/128/${slug}.webp`;
  // Fall back to the global name→shortname resolver so loot rows that aren't in
  // the curated map above still get an icon. Grouped rows like
  // "Rifle Body / SMG Body" contain a slash and are left iconless.
  if (name.includes('/')) return null;
  return iconUrlFromName(name, 128);
}
